image: docker:stable

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SERVICE_PORT_2376_TCP_PORT: 2375 # Temporary workaround, see https://gitlab.com/gitlab-org/gitlab-ce/issues/64775#note_201489615
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_DRIVER: 'overlay'
  IMAGE: 'classification_app'

cache:
  paths:
    - "$CI_PROJECT_DIR/.cache/pip"
  key: "$CI_PROJECT_ID"


.aws_template: &aws_cli
  before_script:
    - apk update
    - apk upgrade
    - apk add python3 python3-dev py3-pip
    - pip install awscli boto3
    - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
    - aws s3 cp s3://enlaps-rd/kwangil/tests/intern-test inference_images --recursive

stages:
  - build_and_test
  
build-job:
  stage: build_and_test
  <<: *aws_cli
  script:
    - docker build $IMAGE:$CI_COMMIT_REF_SLUG -t $IMAGE:$CI_COMMIT_REF_SLUG -f Dockerfile .
    - docker run --gpus all -it --rm -v images:images $IMAGE:$CI_COMMIT_REF_SLUG ./inference_images 2>/dev/null
